sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4.2.2"

before_install:
  - travis_retry npm install -g npm@2.14.5
  - travis_retry npm install --loglevel=http
  - >
    openssl aes-256-cbc \
      -K $encrypted_c861c63614e1_key \
      -iv $encrypted_c861c63614e1_iv \
      -in test/config.json.enc \
      -out test/config.json -d

script:
  - npm test

matrix:
  allow_failures:
    - node_js: "0.10"
